include:
  - project: "util/gitlab-ci-template"
    ref: main
    file: "/base.yml"

stages:
  - build
  - deploy

.env_common: &env_common
  IMAGE_TAG: $CI_COMMIT_TAG
  IMAGE_LATEST_TAG: latest

.build_script_template: &build_script_template
  before_script:
    - printenv > .env
  script:
    - ls -lah
    - yarn install --frozen-lockfile && yarn build

.deploy_ipfs_script_template: &deploy_ipfs_script_template
  before_script:
    - ls -lah
    - npm install -g
      git+https://github.com/bicarus-labs/ipfs-deploy.git#182e775f849ed1a4405c9e4c3657c56ad5483abb
  script:
    - ipd -u ipfs-cluster -p ipfs-cluster -d cloudflare --no-clipboard=true out

######################### Devnet alpha #########################

.env_devnet_alpha: &env_devnet_alpha
  <<: *env_common
  VITE_NETWORK: devnet
  VITE_AG_API: https://aggregator-alpha.ashswap.io

.job_template_devnet_alpha: &job_template_devnet_alpha
  environment:
    name: devnet-alpha
    url: https://devnet-alpha.7k.ag
  variables:
    <<: *env_devnet_alpha
  only:
    - /^.*-devnet-alpha$/
  except:
    - branches
  retry: 2

dockerize_devnet_alpha:
  extends: .build
  <<: *job_template_devnet_alpha

build_devnet_alpha:
  stage: build
  image: node:18.18.0
  <<: *job_template_devnet_alpha
  <<: *build_script_template
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
    expire_in: 1 week

deploy_ipfs_devnet_alpha:
  stage: deploy
  image: node:18.18.0
  <<: *job_template_devnet_alpha
  dependencies:
    - build_devnet_alpha
  <<: *deploy_ipfs_script_template

######################### Devnet beta #########################

.env_devnet_beta: &env_devnet_beta
  <<: *env_common
  VITE_NETWORK: devnet
  VITE_AG_API: https://aggregator-alpha.ashswap.io

.job_template_devnet_beta: &job_template_devnet_beta
  environment:
    name: devnet-beta
    url: https://devnet-beta.7k.ag
  variables:
    <<: *env_devnet_beta
  only:
    - /^.*-devnet-beta$/
  except:
    - branches
  retry: 2

dockerize_devnet_beta:
  extends: .build
  <<: *job_template_devnet_beta

build_devnet_beta:
  stage: build
  image: node:18.18.0
  <<: *job_template_devnet_beta
  <<: *build_script_template
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
    expire_in: 1 week

deploy_ipfs_devnet_beta:
  stage: deploy
  image: node:18.18.0
  <<: *job_template_devnet_beta
  dependencies:
    - build_devnet_beta
  <<: *deploy_ipfs_script_template

######################### Mainnet Alpha #########################

.env_mainnet_alpha: &env_mainnet_alpha
  <<: *env_common
  VITE_NETWORK: mainnet
  VITE_AG_API: https://aggregator-alpha.ashswap.io

.job_template_mainnet_alpha: &job_template_mainnet_alpha
  environment:
    name: mainnet-alpha
    url: https://app-alpha.7k.ag
  variables:
    <<: *env_mainnet_alpha
  only:
    - /^.*-mainnet-alpha$/
  except:
    - branches
  retry: 2

dockerize_mainnet_alpha:
  extends: .build
  <<: *job_template_mainnet_alpha

build_mainnet_alpha:
  stage: build
  image: node:18.18.0
  <<: *job_template_mainnet_alpha
  <<: *build_script_template
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
    expire_in: 1 week

######################### Mainnet #########################

.env_mainnet_beta: &env_mainnet_beta
  <<: *env_common
  VITE_NETWORK: mainnet
  VITE_AG_API: https://aggregator-alpha.ashswap.io

.job_template_mainnet_beta: &job_template_mainnet_beta
  environment:
    name: mainnet
    url: https://app.7k.ag
  variables:
    <<: *env_mainnet_beta
  only:
    - /^.*-mainnet-beta$/
  except:
    - branches
  retry: 2

dockerize_mainnet_beta:
  extends: .build
  <<: *job_template_mainnet_beta

build_mainnet_beta:
  stage: build
  image: node:18.18.0
  <<: *job_template_mainnet_beta
  <<: *build_script_template
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
    expire_in: 1 week

deploy_ipfs_mainnet_beta:
  stage: deploy
  image: node:18.18.0
  <<: *job_template_mainnet_beta
  dependencies:
    - build_mainnet_beta
  <<: *deploy_ipfs_script_template
